apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
  name: guestbook-ui-no-prune
  labels:
    app: guestbook-ui-no-prune
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui-no-prune
  template:
    metadata:
      labels:
        app: guestbook-ui-no-prune
    spec:
      containers:
      - image: gcr.io/google-samples/gb-frontend:v5
        name: guestbook-ui
        ports:
        - containerPort: 80
